version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_TIMEOUT: 60
      SQLALCHEMY_DATABASE_URI: postgresql://kaypoh:youreallykaypoh@postgres:5432/kaypoh
    volumes:
      - ./backend/:/backend/
    command: ["./cmd", "dev-run"]
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: kaypoh
      POSTGRES_PASSWORD: youreallykaypoh
      POSTGRES_USER: kaypoh
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
    postgres:
