version: '3.8'

services:
  # server runs periodic tasks and interacts with database
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_TIMEOUT: 60
      SQLALCHEMY_DATABASE_URI: postgresql://kaypoh:youreallykaypoh@postgres:5432/kaypoh
    volumes:
      - ./backend/:/backend/
      - ./data/:/backend/data/
    command:
      ["./cmd", "dev-run"]
    ports:
      - 8000:8000
    depends_on:
      - postgres

  # bot polls for user updates
  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - ./listener/:/listener/
      - ./data/:/listener/data/
    command:
      ["python3", "main_bot.py"]

  # bot broadcasts
  broadcaster:
    build:
      context: ./broadcaster
      dockerfile: Dockerfile
    environment:
      EVENT_AGGREGATION_INTERVAL: 60
    env_file: .env
    ports:
      - 5001:5001
    depends_on:
      - listener
    volumes:
      - ./listener/:/listener/
      - ./broadcaster/:/broadcaster/
      - ./data/:/broadcaster/data/
    command:
      ["python3", "broadcaster_bot.py"]

  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: kaypoh
      POSTGRES_PASSWORD: youreallykaypoh
      POSTGRES_USER: kaypoh
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
    postgres:
